project:
#  title: "Hugo-Lopez-Pena.github.io"
  type: website
  output-dir: docs

website:
  title: "Hugo López Peña"
  navbar:
    left:
      - href: index.md
        text: Home
      - href: snipets/xtb_ohess_catmos_commented.ipynb
        text: xtb

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true


